name: tests

on: [push, pull_request]

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install OS packages
        run: |
          sudo apt-get update
          sudo apt-get install libopus-dev libvpx-dev
      - name: Build documentation
        run: |
          pip install . -r requirements/doc.txt
          make -C docs html SPHINXOPTS=-W

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install OS packages
        run: |
          sudo apt-get update
          sudo apt-get install libopus-dev libvpx-dev
      - name: Run linters
        run: |
          pip install . -r requirements/lint.txt
          ruff check .
          ruff format --check --diff .
          check-manifest
          mypy src

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python:
          - '3.13'
          - '3.12'
          - '3.11'
          - '3.10'
          - '3.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install OS packages and disable firewall
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install opus libvpx
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
      - name: Install OS packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libopus-dev libvpx-dev
      - name: Run tests
        run: |
          python -m pip install -U pip setuptools wheel
          pip install .[dev]
          coverage run -m unittest discover -v
          coverage xml
        shell: bash
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  package-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Build source package
        run: |
          pip install -U build
          python -m build --sdist
      - name: Upload source package
        uses: actions/upload-artifact@v4
        with:
          name: dist-source
          path: dist/

  package-wheel-pyodide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.58'
      - name: Build WebAssembly dependencies
        run: |
          mkdir -p /tmp/wasm-vendor/{include,lib}
          
          # Build Opus
          git clone --depth 1 --branch v1.3.1 https://github.com/xiph/opus.git
          cd opus
          ./autogen.sh
          emconfigure ./configure --prefix=/tmp/wasm-vendor --disable-shared --enable-static
          emmake make -j4
          emmake make install
          cd ..
          
          # Build libvpx (if needed)
          git clone --depth 1 --branch v1.13.1 https://chromium.googlesource.com/webm/libvpx.git
          cd libvpx
          emconfigure ./configure --prefix=/tmp/wasm-vendor --disable-examples --disable-tools --disable-docs --disable-unit-tests --enable-static --disable-shared
          emmake make -j4
          emmake make install
          cd ..
      - name: Build wheels for Pyodide
        env:
          CIBW_PLATFORM: pyodide
          CIBW_ENVIRONMENT: CFLAGS="-I/tmp/wasm-vendor/include" LDFLAGS="-L/tmp/wasm-vendor/lib"
          CIBW_TEST_SKIP: "*"
        run: |
          pip install cibuildwheel>=2.19.0
          cibuildwheel --output-dir dist
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheel-pyodide
          path: dist/
